### ISSUE TITLE
to_svox1 colors

### ISSUE THREAD

**Issue by ookey** [sxyu/svox2#22]
Thanks a lot for your outstanding work!
Experimenting the export to svox1, I find the colors a bit "greyish". I was wondering if the reason is the sigmoid you apply in volrend, which is not applied (as far as I understood) in svox2?

In svox2 `render_lerp_kernel_cuvol.cu` (line 102):
```
            outv += weight * fmaxf(lane_color_total + 0.5f, 0.f);  // Clamp to [+0, infty)
```
In volrend `rt_core.cuh` (line 192):
```
                            out[t] += weight / (1.f + expf(-tmp));
```

It seems to give better colors by just replacing the above line by:
```
                            out[t] += weight * min(1., max(0., tmp + 0.5));
```
What do you think? Did I understand well the fading color problem?

Best regards,
Matthieu.

**Comment by SSground** [comment]
> 非常感谢您的出色工作！ 尝试导出到 svox1，我发现颜色有点“灰色”。我想知道原因是否是您在 volrend 中应用的 sigmoid，在 svox2 中未应用（据我所知）？
> 
> 在 svox2 `render_lerp_kernel_cuvol.cu`（第 102 行）中：
> 
> ```
>             outv += weight * fmaxf(lane_color_total + 0.5f, 0.f);  // Clamp to [+0, infty)
> ```
> 
> 在 volrend `rt_core.cuh`（第 192 行）中：
> 
> ```
>                             out[t] += weight / (1.f + expf(-tmp));
> ```
> 
> 通过将上面的行替换为以下内容，似乎可以提供更好的颜色：
> 
> ```
>                             out[t] += weight * min(1., max(0., tmp + 0.5));
> ```
> 
> 你怎么认为？我是否理解褪色问题？
> 
> 最好的问候， 马修。

when I use to_svox1.py have a error ![image](https://user-images.githubusercontent.com/27821863/146523789-f5c5edd2-9892-4555-a76e-088e4fd0c57f.png)

**Comment by bolshoytoster** [comment]
> when I use to_svox1.py have a error ![image](https://user-images.githubusercontent.com/27821863/146523789-f5c5edd2-9892-4555-a76e-088e4fd0c57f.png)

That issue has been fixed in the most recent version of svox, try running `pip install -U svox` to update it.

**Comment by SSground** [comment]
> svox

svox2 or svox？

**Comment by ookey** [comment]
Hello,
@SSground , do you confirm the colors are faded out somehow, when you play the result with volrend? or are they correct in your tests?

**Comment by SSground** [comment]
> 你好， @SSground，当你用 volrend 播放结果时，你确认颜色以某种方式淡出吗？或者他们在你的测试中是正确的？
I followed your suggestion, but it still doesn't work.
                            out[t] += weight * min(1., max(0., tmp + 0.5));
do you have anything else to try？

**Comment by walsvid** [comment]
same issue
